production:
  adapter: postgresql
  database: my_database
  username: username
  password: password
  host: localhost

development:
  adapter: postgresql
  database: my_database
  username: username
  password: password
  host: localhost